define({
  "html": {
    AD_FAILED_LOGINS: 'Active Directory\' failed logon tries',
    AS_EMAIL: 'ActiveSync user email',
    BES_EMAIL: 'BES user email',
    COMPANY: 'Company',
    COMPANY_NAME: 'Company name',
    COUNTRY: 'Country',
    DEPT: 'Department',
    DESC: 'Description',
    DISABLED_USER: 'Disabled user',
    DISPLAY_NAME: 'Display name',
    DN: 'Distinguished name',
    DOMAIN_NAME: 'Domain name',
    EMAIL: 'Email',
    FIRST_NAME: 'First name',
    MIDDLE_INIT: 'Middle initial',
    MOBILE: 'Mobile',
    NAME: 'Name',
    OFFICE_ADDRESS: 'Office address',
    OFFICE_CITY: 'Office city',
    OFFICE_FAX: 'Office fax number',
    OFFICE_STATE: 'Office state/province',
    OFFICE_STREET: 'Office street address',
    OFFICE_PHONE: 'Office telephone number',
    OFFICE_ZIP: 'Office zip or post code',
    OTHER: 'Other',
    POBOX: 'P.O box',
    GROUP_ID: 'Primary group ID',
    SAM_ACCOUNT: 'SAM account',
    SURNAME: 'Surname',
    TITLE: 'Title',
    LOGIN_NAME: 'User logon name',
    ASM_PERSON_ID: "ASM person ID",
    ASM_PERSON_MANAGED_APPLE_ID: "ASM managed Apple ID",
    ASM_PERSON_PASSCODE_TYPE: "ASM passcode type",
    ASM_PERSON_SOURCE: "ASM data source",
    ASM_PERSON_SOURCE_SYSTEM_ID: "ASM source\" system ID",
    ASM_PERSON_GRADE: "ASM student grade",
    ASM_PERSON_STATUS: "ASM person status",
    ASM_PERSON_TITLE: "ASM person title",
    ASM_PERSON_UNIQUE_ID: "ASM person unique ID",
    MIDDLE_NAME: "Middle name"
  }
});